[build]
command = "rm -rf node_modules pnpm-lock.yaml && CI='' pnpm install --force --reporter=ndjson && pnpm build"
publish = "docs"

[build.environment]
NODE_VERSION = "18.18.0"
PNPM_VERSION = "8.15.9"  # 与本地版本一致
NPM_FLAGS = "--frozen-lockfile"
